<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.0.0</Version>
    <!-- Manifest fields (see https://github.com/goatcorp/DalamudPackager/blob/827d88dc/DalamudPackager/DalamudPackager.cs#L420) -->
    <Author>Stinguim(Taigo)</Author>
    <Name>LootGoblin</Name>
    <Punchline>Check what everyone rolled for loot!</Punchline>
    <Description>This plugin allows the user to verify with every chest what anyone rolled/passed. Works better in trials for mount farming.</Description>
    <RepoUrl>https://github.com/Stinguim/Loot-Goblin-FF14</RepoUrl>
    <Tags>loot;plugin;rolls;roll</Tags>
  </PropertyGroup>
</Project>
